"""Constants for the Qingping IoT Cloud integration."""

DOMAIN = "qingping_iot_cloud"

DEFAULT_SCAN_INTERVAL = 300
MIN_SCAN_INTERVAL = 60
MAX_DELAY_MULTIPLIER=3

HTTP_GET_TIMEOUT = 60

MIN_COLLECT_INTERVAL = 1
MIN_REPORT_INTERVAL = 60
